<?php

namespace App\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MantenimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MantenimientoRepository extends EntityRepository
{
    public function findDatosMantenimiento()
    {
        $em = $this->getEntityManager();
        $dql = "select m,a from AdminBundle:Mantenimiento m join m.afiliacion a";
        $consulta = $em->createQuery($dql);
        $reg = $consulta->getResult();
        return $reg;
    }
    
    public function findMantenimientos()
    {
        $em = $this->getEntityManager();
        $dql = "select m,a,t,p from AdminBundle:Mantenimiento m join m.afiliacion a join m.tecnico t join m.problema p";
        $consulta = $em->createQuery($dql);
        $reg = $consulta->getResult();
        return $reg;
    }
    
    public function findMantenimiento($ind)
    {
        $em = $this->getEntityManager();
        $dql = "select m,a,t,p from AdminBundle:Mantenimiento m join m.afiliacion a join m.tecnico t join m.problema p where m.id=:bandera";
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('bandera',$ind);
        $reg = $consulta->getSingleResult();
        return $reg;
    }
    
}
