security:
    encoders:
        App\AdminBundle\Entity\Administrador:
           algorithm: sha512
           encode-as-base64: true
           iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
           entity: {class: App\AdminBundle\Entity\Administrador, property: usuario}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        frontend:
            pattern:    ^/*
            provider: usuarios
            anonymous: ~
            form_login:
                check_path: usuario_login_check
                login_path: usuario_login
            logout:
                path:   usuario_logout
                target: /

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_ADMIN }
